# Generated by Django 3.2.5 on 2021-08-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='prefix',
            field=models.IntegerField(choices=[(1, 'นาย'), (2, 'นางสาว'), (3, 'นาง')]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
