# Generated by Django 3.2.5 on 2021-08-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_article_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
